### ISSUE TITLE
tramp(ssh)をサポートする

### ISSUE THREAD

**Issue by ncaq** [ncaq/auto-sudoedit#10]
ssh接続する時はroot使えば問題にならないけどAWSとかで面倒

**Comment by brandonpollack23** [comment]
私もこの機能を使いたいと思います：

この具合ですね：
自分が持つサーバーやリモートホストにTRAMPで繋がる時

そちらのRootが待つファイル（例えば、/etc/のファイル）を編集したい時

オートSudoeditが何もせず続いてて、新たなファイルを保存できません。いつもみたいみ（このプラッグインを使う前みたいに）Find-Fileを利用して、/ssh:USER@remote|sudo::/PATH　をしないといけいないようです。ロカルに比べて不便ですね。

その代わり、ローカルファイルのようにRootのパスワードを聞いて欲しいと思います。

この機能は可能ですか？

このすごく便利なプラッグインを作って、ありがとうございます！

PS:　母国語は日本語ではありません、お許しください。

**Comment by ncaq** [comment]
可能なので時間が出来れば実装したいと思っています
