### ISSUE TITLE
Feature upstreaming

### ISSUE THREAD

**Issue by yvie-k** [ncaq/auto-sudoedit#14]
Hi :wave: 
I did some customizations for my use-case: https://github.com/Dragoncraft89/auto-sudoedit/commit/7c70781833ce2b04d22f6de27ce9443bcdbdf413

Now, I'm wondering what parts you'd like me to contribute back upstream. Here's a list of my changes:

# Bug fixes
- Sudo syntax over tramp was wrong, which made reopen as sudo trying to open an invalid file when using tramp

# Features
- advice-add doesn't work when you use a different find-file function (such as ido-find-file). This may be the problem observed in #11 . I solved this by using the find-file-hook instead.
- Added a `y-or-no-p` query before reopening the buffer. This allows you to open files when you don't have sudo permissions (e.g. via tramp on other people's machines)
- Added auto-detection of the user owning a file. Therefore auto-sudoedit can reopen files as other users beside root (e.g. as www-data)

Just tell me whether you'd like me to upstream some of these changes and I'll happily prepare a pull request

**Comment by ncaq** [comment]
At a quick glance, I think they are all great changes.
I would like to take them all in and would like to have a PR open.
